//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aff.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfig
    {
        public int ConfigId { get; set; }
        public double PercentAmount { get; set; }
        public double PercentRefer { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    }
}
