//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aff.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int PaymentId { get; set; }
        public int UserId { get; set; }
        public long AmountEarning { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> VerifyStatus { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string AccountInfo { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
