//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aff.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public long ReportId { get; set; }
        public long TransactionId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserReferId { get; set; }
        public Nullable<long> TransactionAmount { get; set; }
        public Nullable<double> PercentAmount { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<long> LoanId { get; set; }
        public Nullable<long> LenderId { get; set; }
    
        public virtual tblTransaction tblTransaction { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
