//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aff.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTransaction()
        {
            this.tblReports = new HashSet<tblReport>();
        }
    
        public long TransactionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> LoanId { get; set; }
        public Nullable<long> LenderId { get; set; }
        public Nullable<int> Status { get; set; }
        public string AffCode { get; set; }
        public Nullable<double> PercentAmount { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ProductCreditId { get; set; }
    
        public virtual tblLoan tblLoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReport> tblReports { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
