//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aff.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserReport
    {
        public long UserReportId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<long> TotalAvailableAmount { get; set; }
        public Nullable<long> TranferAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Note { get; set; }
        public string DataOfMonth { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
