//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aff.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViewCount
    {
        public long Id { get; set; }
        public string AffCode { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
